# Not happy with the default? Customize the rules depending on your needs.
# Here are some examples:
linter:
  rules:
    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Back to the 80s
    lines_longer_than_80_chars: true

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false
