name: marketplace_nuconta
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

scripts:
  get: flutter packages get
  appicon: flutter pub run flutter_launcher_icons:main -f pubspec.yaml
  apk: flutter build apk
  test: flutter test --coverage ./lib
  coverage: genhtml -o coverage coverage/lcov.info & xdg-open coverage/index-sort-l.html #works on linux

dependencies:
  flutter:
    sdk: flutter
  lint: ^1.7.2
  get:
  intl:
  cached_network_image: ^3.1.0+1
  network_image_mock: ^2.0.1
  cupertino_icons: ^1.0.2
  graphql: ^5.0.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner:

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/app/assets/images/loading_dots.gif
    - .env

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: lib/app/assets/fonts/Roboto-Black.ttf
  #       - asset: lib/app/assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: lib/app/assets/fonts/Roboto-Light.ttf
  #       - asset: lib/app/assets/fonts/Roboto-Medium.ttf
  #       - asset: lib/app/assets/fonts/Roboto-Regular.ttf
