name: Run Tests

on:
  workflow_call:
    secrets:
      DOTENV:
        required: true
  push:
    branches:
      - main

env:
  flutter_version: "2.5.3"

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
      - name: get enviromnets
        run: echo ${{ secrets.DOTENV }} | base64 -d > .env
      - name: Run pub get
        run: flutter pub get

      - uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./lib
      - name: Run tests
        run: flutter test --coverage ./lib >
      - name: Run tests
        run: flutter test --coverage ./lib >
